insert into user
select a.* from JSON_TABLE('[
    {
        "id": 1,
        "firstName": "Terry",
        "lastName": "Medhurst",
        "maidenName": "Smitham",
        "gender": "male",
        "email": "atuny0@sohu.com",
        "phone": "+63 791 675 8914",
        "username": "atuny0",
        "password": "9uQFF1Lh",
        "birthDate": "2000-12-25 03:14:07",
        "image": "https://robohash.org/hicveldicta.png",
        "height": 189,
        "weight": 75.4,
        "address":  "1745 T Street Southeast Washington"
    },
    {
        "id": 2,
        "firstName": "Sheldon",
        "lastName": "Quigley",
        "maidenName": "Cole",
        "gender": "male",
        "email": "hbingley1@plala.or.jp",
        "phone": "+7 813 117 7139",
        "username": "hbingley1",
        "password": "CQutx25i8r",
        "birthDate": "2003-08-02 03:14:07",
        "image": "https://robohash.org/doloremquesintcorrupti.png",
        "height": 187,
        "weight": 74,
        "address": "6007 Applegate Lane Louisville"
    },
    {
        "id": 3,
        "firstName": "Terrill",
        "lastName": "Hills",
        "maidenName": "Hoeger",
        "gender": "male",
        "email": "rshawe2@51.la",
        "phone": "+63 739 292 7942",
        "username": "rshawe2",
        "password": "OWsTbMUgFc",
        "birthDate": "1992-12-30 03:14:07",
        "image": "https://robohash.org/consequunturautconsequatur.png",
        "height": 200,
        "weight": 105.3,
        "address": "560 Penstock Drive Grass Valley"
    },
    {
        "id": 4,
        "firstName": "Miles",
        "lastName": "Cummerata",
        "maidenName": "Maggio",
        "gender": "male",
        "email": "yraigatt3@nature.com",
        "phone": "+86 461 145 4186",
        "username": "yraigatt3",
        "password": "sRQxjPfdS",
        "birthDate": "1969-01-16 03:14:07",
        "image": "https://robohash.org/facilisdignissimosdolore.png",
        "height": 157,
        "weight": 95.9,
        "address": "150 Carter Street Manchester"
    },
    {
        "id": 5,
        "firstName": "Mavis",
        "lastName": "Schultz",
        "maidenName": "Yundt",
        "gender": "male",
        "email": "kmeus4@upenn.edu",
        "phone": "+372 285 771 1911",
        "username": "kmeus4",
        "password": "aUTdmmmbH",
        "birthDate": "1968-11-03 03:14:07",
        "image": "https://robohash.org/adverovelit.png",
        "height": 188,
        "weight": 106.3,
        "address": "2721 Lindsay Avenue Louisville"
    },
    {
        "id": 6,
        "firstName": "Alison",
        "lastName": "Reichert",
        "maidenName": "Franecki",
        "gender": "female",
        "email": "jtreleven5@nhs.uk",
        "phone": "+351 527 735 3642",
        "username": "jtreleven5",
        "password": "zY1nE46Zm",
        "birthDate": "1969-07-21 03:14:07",
        "image": "https://robohash.org/laboriosamfacilisrem.png",
        "height": 149,
        "weight": 105.7,
        "eyeColor": "Amber",
        "domain": "bandcamp.com",
        "address": "18 Densmore Drive Essex"
    },
    {
        "id": 7,
        "firstName": "Oleta",
        "lastName": "Abbott",
        "maidenName": "Wyman",
        "gender": "female",
        "email": "dpettegre6@columbia.edu",
        "phone": "+62 640 802 7111",
        "username": "dpettegre6",
        "password": "YVmhktgYVS",
        "birthDate": "1982-02-21 03:14:07",
        "image": "https://robohash.org/cupiditatererumquos.png",
        "height": 172,
        "weight": 78.1,
        "address": "637 Britannia Drive Vallejo"
    },
    {
        "id": 8,
        "firstName": "Ewell",
        "lastName": "Mueller",
        "maidenName": "Durgan",
        "gender": "male",
        "email": "ggude7@chron.com",
        "phone": "+86 946 297 2275",
        "username": "ggude7",
        "password": "MWwlaeWcOoF6",
        "birthDate": "1964-08-24 03:14:07",
        "image": "https://robohash.org/quiaharumsapiente.png",
        "height": 146,
        "weight": 52.1,
        "address": "5601 West Crocus Drive Glendale"
    },
    {
        "id": 9,
        "firstName": "Demetrius",
        "lastName": "Corkery",
        "maidenName": "Gleason",
        "gender": "male",
        "email": "nloiterton8@aol.com",
        "phone": "+86 356 590 9727",
        "username": "nloiterton8",
        "password": "HTQxxXV9Bq4",
        "birthDate": "1971-03-11 03:14:07",
        "image": "https://robohash.org/excepturiiuremolestiae.png",
        "height": 170,
        "weight": 97.1,
        "address": "5403 Illinois Avenue Nashville"
    },
    {
        "id": 10,
        "firstName": "Eleanora",
        "lastName": "Price",
        "maidenName": "Cummings",
        "gender": "female",
        "email": "umcgourty9@jalbum.net",
        "phone": "+60 184 408 0824",
        "username": "umcgourty9",
        "password": "i0xzpX",
        "birthDate": "1958-08-11 03:14:07",
        "image": "https://robohash.org/aliquamcumqueiure.png",
        "height": 198,
        "weight": 48,
        "address": "8821 West Myrtle Avenue Glendale"
    },
    {
        "id": 11,
        "firstName": "Marcel",
        "lastName": "Jones",
        "maidenName": "Smith",
        "gender": "male",
        "email": "acharlota@liveinternet.ru",
        "phone": "+967 253 210 0344",
        "username": "acharlota",
        "password": "M9lbMdydMN",
        "birthDate": "1961-09-12 03:14:07",
        "image": "https://robohash.org/impeditautest.png",
        "height": 203,
        "weight": 63.7,
        "address": "2203 7th Street Road Louisville"
    },
    {
        "id": 12,
        "firstName": "Assunta",
        "lastName": "Rath",
        "maidenName": "Heller",
        "gender": "female",
        "email": "rhallawellb@dropbox.com",
        "phone": "+380 962 542 6549",
        "username": "rhallawellb",
        "password": "esTkitT1r",
        "birthDate": "1990-12-14 03:14:07",
        "image": "https://robohash.org/namquaerataut.png",
        "height": 168,
        "weight": 96.8,
        "address": "6463 Vrain Street Arvada"
    },
    {
        "id": 13,
        "firstName": "Trace",
        "lastName": "Douglas",
        "maidenName": "Lemke",
        "gender": "male",
        "email": "lgribbinc@posterous.com",
        "phone": "+1 609 937 3468",
        "username": "lgribbinc",
        "password": "ftGj8LZTtv9g",
        "birthDate": "1967-07-23 03:14:07",
        "image": "https://robohash.org/voluptatemsintnulla.png",
        "height": 181,
        "weight": 56.5,
        "address": "87 Horseshoe Drive West Windsor"
    },
    {
        "id": 14,
        "firstName": "Enoch",
        "lastName": "Lynch",
        "maidenName": "Heidenreich",
        "gender": "male",
        "email": "mturleyd@tumblr.com",
        "phone": "+94 912 100 5118",
        "username": "mturleyd",
        "password": "GyLnCB8gNIp",
        "birthDate": "1979-08-25 03:14:07",
        "image": "https://robohash.org/quisequienim.png",
        "height": 150,
        "weight": 100.3,
        "address": "60 Desousa Drive Manchester"
    },
    {
        "id": 15,
        "firstName": "Jeanne",
        "lastName": "Halvorson",
        "maidenName": "Cummerata",
        "gender": "female",
        "email": "kminchelle@qq.com",
        "phone": "+86 581 108 7855",
        "username": "kminchelle",
        "password": "0lelplR",
        "birthDate": "1996-02-02 03:14:07",
        "image": "https://robohash.org/autquiaut.png",
        "height": 176,
        "weight": 45.7,
        "address": "4 Old Colony Way Yarmouth"
    },
    {
        "id": 16,
        "firstName": "Trycia",
        "lastName": "Fadel",
        "maidenName": "Rosenbaum",
        "gender": "female",
        "email": "dpierrof@vimeo.com",
        "phone": "+420 833 708 0340",
        "username": "dpierrof",
        "password": "Vru55Y4tufI4",
        "birthDate": "1963-07-03 03:14:07",
        "image": "https://robohash.org/porronumquamid.png",
        "height": 166,
        "weight": 87.2,
        "address": "314 South 17th Street Nashville"
    },
    {
        "id": 17,
        "firstName": "Bradford",
        "lastName": "Prohaska",
        "maidenName": "Bins",
        "gender": "male",
        "email": "vcholdcroftg@ucoz.com",
        "phone": "+420 874 628 3710",
        "username": "vcholdcroftg",
        "password": "mSPzYZfR",
        "birthDate": "1975-10-20 03:14:07",
        "image": "https://robohash.org/accusantiumvoluptateseos.png",
        "height": 199,
        "weight": 94.3,
        "address": "1649 Timberridge Court Fayetteville"
    },
    {
        "id": 18,
        "firstName": "Arely",
        "lastName": "Skiles",
        "maidenName": "Monahan",
        "gender": "male",
        "email": "sberminghamh@chron.com",
        "phone": "+55 886 766 8617",
        "username": "sberminghamh",
        "password": "cAjfb8vg",
        "birthDate": "1958-02-05 03:14:07",
        "image": "https://robohash.org/nihilharumqui.png",
        "height": 192,
        "weight": 97,
        "address": "5461 West Shades Valley Drive Montgomery"
    },
    {
        "id": 19,
        "firstName": "Gust",
        "lastName": "Purdy",
        "maidenName": "Abshire",
        "gender": "male",
        "email": "bleveragei@so-net.ne.jp",
        "phone": "+86 886 889 0258",
        "username": "bleveragei",
        "password": "UZGAiqPqWQHQ",
        "birthDate": "1989-10-15 03:14:07",
        "image": "https://robohash.org/delenitipraesentiumvoluptatum.png",
        "height": 167,
        "weight": 65.3,
        "address": "629 Debbie Drive Nashville"
    },
    {
        "id": 20,
        "firstName": "Lenna",
        "lastName": "Renner",
        "maidenName": "Schumm",
        "gender": "female",
        "email": "aeatockj@psu.edu",
        "phone": "+1 904 601 7177",
        "username": "aeatockj",
        "password": "szWAG6hc",
        "birthDate": "1980-01-19 03:14:07",
        "image": "https://robohash.org/ipsumutofficiis.png",
        "height": 175,
        "weight": 68,
        "address": "22572 Toreador Drive Salinas"
    },
    {
        "id": 21,
        "firstName": "Doyle",
        "lastName": "Ernser",
        "maidenName": "Feeney",
        "gender": "male",
        "email": "ckensleyk@pen.io",
        "phone": "+86 634 419 6839",
        "username": "ckensleyk",
        "password": "tq7kPXyf",
        "birthDate": "1983-01-22 03:14:07",
        "image": "https://robohash.org/providenttemporadelectus.png",
        "height": 173,
        "weight": 69.9,
        "address": "3034 Mica Street Fayetteville"
    },
    {
        "id": 22,
        "firstName": "Tressa",
        "lastName": "Weber",
        "maidenName": "Williamson",
        "gender": "female",
        "email": "froachel@howstuffworks.com",
        "phone": "+34 517 104 6248",
        "username": "froachel",
        "password": "rfVSKImC",
        "birthDate": "1987-11-11 03:14:07",
        "image": "https://robohash.org/temporarecusandaeest.png",
        "height": 164,
        "weight": 87.1,
        "address": "3729 East Mission Boulevard Fayetteville"
    },
    {
        "id": 23,
        "firstName": "Felicity",
        "lastName": "O Reilly",
        "maidenName": "Rosenbaum",
        "gender": "female",
        "email": "beykelhofm@wikispaces.com",
        "phone": "+63 919 564 1690",
        "username": "beykelhofm",
        "password": "zQwaHTHbuZyr",
        "birthDate": "1967-10-05 03:14:07",
        "image": "https://robohash.org/odioquivero.png",
        "height": 151,
        "weight": 96.7,
        "address": "5114 Greentree Drive Nashville"
    },
    {
        "id": 24,
        "firstName": "Jocelyn",
        "lastName": "Schuster",
        "maidenName": "Dooley",
        "gender": "male",
        "email": "brickeardn@fema.gov",
        "phone": "+7 968 462 1292",
        "username": "brickeardn",
        "password": "bMQnPttV",
        "birthDate": "1966-06-02 03:14:07",
        "image": "https://robohash.org/odiomolestiaealias.png",
        "height": 166,
        "weight": 93.3,
        "address": "3466 Southview Avenue Montgomery"
    },
    {
        "id": 25,
        "firstName": "Edwina",
        "lastName": "Ernser",
        "maidenName": "Kiehn",
        "gender": "female",
        "email": "dfundello@amazon.co.jp",
        "phone": "+86 376 986 8945",
        "username": "dfundello",
        "password": "k9zgV68UKw8m",
        "birthDate": "2000-09-28 03:14:07",
        "image": "https://robohash.org/doloremautdolores.png",
        "height": 180,
        "weight": 102.1,
        "address": "1513 Cathy Street Savannah"
    },
    {
        "id": 26,
        "firstName": "Griffin",
        "lastName": "Braun",
        "maidenName": "Deckow",
        "gender": "male",
        "email": "lgronaverp@cornell.edu",
        "phone": "+62 511 790 0161",
        "username": "lgronaverp",
        "password": "4a1dAKDv9KB9",
        "birthDate": "1965-09-06 03:14:07",
        "image": "https://robohash.org/laboriosammollitiaut.png",
        "height": 146,
        "weight": 65.5,
        "address": "600 West 19th Avenue Anchorage"
    },
    {
        "id": 27,
        "firstName": "Piper",
        "lastName": "Schowalter",
        "maidenName": "Wuckert",
        "gender": "female",
        "email": "fokillq@amazon.co.jp",
        "phone": "+60 785 960 7918",
        "username": "fokillq",
        "password": "xZnWSWnqH",
        "birthDate": "1983-06-07 03:14:07",
        "image": "https://robohash.org/nequeodiosapiente.png",
        "height": 197,
        "weight": 71.5,
        "address": "1208 Elkader Court North Nashville"
    },
    {
        "id": 28,
        "firstName": "Kody",
        "lastName": "Terry",
        "maidenName": "Larkin",
        "gender": "male",
        "email": "xisherwoodr@ask.com",
        "phone": "+81 859 545 8951",
        "username": "xisherwoodr",
        "password": "HLDqN5vCF",
        "birthDate": "1979-01-09 03:14:07",
        "image": "https://robohash.org/consequunturabnon.png",
        "height": 172,
        "weight": 90.2,
        "address": "210 Green Road Manchester"
    },
    {
        "id": 29,
        "firstName": "Macy",
        "lastName": "Greenfelder",
        "maidenName": "Koepp",
        "gender": "female",
        "email": "jissetts@hostgator.com",
        "phone": "+81 915 649 2384",
        "username": "jissetts",
        "password": "ePawWgrnZR8L",
        "birthDate": "1976-09-07 03:14:07",
        "image": "https://robohash.org/amettemporeea.png",
        "height": 166,
        "weight": 93.7,
        "address": "49548 Road 200 O Neals"
    },
    {
        "id": 30,
        "firstName": "Maurine",
        "lastName": "Stracke",
        "maidenName": "Abshire",
        "gender": "female",
        "email": "kdulyt@umich.edu",
        "phone": "+48 143 590 6847",
        "username": "kdulyt",
        "password": "5t6q4KC7O",
        "birthDate": "1964-12-18 03:14:07",
        "image": "https://robohash.org/perferendisideveniet.png",
        "height": 170,
        "weight": 107.2,
        "address": "81 Seaton Place Northwest Washington"
    }
]', 

    '$[*]' COLUMNS(
            idUser int PATH '$.id', 
            firstname varchar(254) PATH '$.firstName', 
            lastname varchar(254) path '$.lastName',
            maidenName varchar(254) path '$.maidenName',
            gender varchar(254) path '$.gender',
			email varchar(254) path '$.email',
			phone varchar(254) path '$.phone',
			username varchar(254) path '$.username',
			password varchar(254) path '$.password',
			birthdate datetime path '$.birthDate',
			image varchar(254) path '$.image',
			height int path '$.height',
			weight int path '$.weight',
			address varchar(254) path '$.address'
        )) a;